### ISSUE TITLE
needs better `db` folder management

### ISSUE THREAD

**Issue by kitschbent** [hoprnet/hopr-sh#3]
At present, this script just looks for a previously named `db` folder, renames it to preserve this folder, etc...  Its very messy, was a quick solution, and creates problems when run multiple times (2+). Or if the person manually starts renaming folders in certain ways, which also happened.

Ideally, this part of this script needs addressing specifically or we need some sort of less-crude `db` folder management. If only to get us from testnet to testnet in a better, more reliable manner (especially currently as we have a string between Dec's and this upcoming to address and need to keep wallet addresses, ideally)

`install-uni.sh`

I'm hesitant to just address it myself as its hacking a hacked job. It works, but its not pretty.

**Comment by kitschbent** [comment]
@peterbraden

**Comment by nionis** [comment]
@kitschbent currently, the script doesn't do that - I want this to be as simple as possible, it should be a script that users can run and get started quick

**Comment by kitschbent** [comment]
Agree, provided we dont wipe db folders with a restart of node. This was
cause of including this, we would wipe out the an and get new address and
need to re fund. Obviously, want to avoid this with community, they *will*
be restarting no doubt, and some regularly. Even if we tell them to not...

**Comment by nionis** [comment]
@kitschbent that doesn't happen now 👍 , closing issue
