### ISSUE TITLE
wget not using the raw path

### ISSUE THREAD

**Issue by gpersoon** [hoprnet/hopr-sh#4]
The path for wget in the following doc is wrong:
https://github.com/hoprnet/hopr-sh/blob/main/README.md

```JS
wget https://github.com/hoprnet/hopr-sh/blob/master/install-uni.sh
```
Should be:
```JS
wget https://raw.githubusercontent.com/hoprnet/hopr-sh/main/install-uni.sh
```

**Comment by kitschbent** [comment]
@jjperezaguinaga ^^

**Comment by nionis** [comment]
thanks @gpersoon , already fixed in the upcoming update https://github.com/hoprnet/hopr-sh/pull/5
